# Generated by Django 3.0.3 on 2020-02-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchres',
            old_name='negetive',
            new_name='negative',
        ),
    ]
