# Generated by Django 3.0.4 on 2020-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0003_auto_20200214_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('dorm', models.PositiveIntegerField(default=0)),
                ('countofdorm', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='searchres',
            name='negitweet1',
        ),
        migrations.RemoveField(
            model_name='searchres',
            name='negitweet2',
        ),
        migrations.RemoveField(
            model_name='searchres',
            name='positweet1',
        ),
        migrations.RemoveField(
            model_name='searchres',
            name='positweet2',
        ),
        migrations.AlterField(
            model_name='searchres',
            name='negative',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='searchres',
            name='positive',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='searchres',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
