# Generated by Django 3.0.4 on 2020-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0004_auto_20200315_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchres',
            name='negtweet1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='searchres',
            name='negtweet2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='searchres',
            name='postweet1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='searchres',
            name='postweet2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
