# Generated by Django 3.0.4 on 2020-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0005_auto_20200316_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed',
            name='negative',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detailed',
            name='positive',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detailed',
            name='time1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detailed',
            name='tweetcount',
            field=models.IntegerField(default=1000),
        ),
    ]
