# Generated by Django 3.0.4 on 2020-03-28 18:46

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0006_auto_20200321_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchres',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
            preserve_default=False,
        ),
    ]
