# Generated by Django 3.0.4 on 2020-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0008_auto_20200329_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchres',
            name='negwc',
            field=models.CharField(default='', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='searchres',
            name='poswc',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
