# Generated by Django 3.0.4 on 2020-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqres', '0009_auto_20200329_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed',
            name='negwc',
            field=models.CharField(default='', max_length=10000000),
        ),
        migrations.AddField(
            model_name='detailed',
            name='poswc',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
